"""
Utility for building Google Calendar events from tennis match data.
"""

import hashlib
from datetime import datetime, timedelta
from typing import Optional


def build_calendar_event(match: dict, followed_player_name: Optional[str] = None) -> dict:
    """
    Convert Tennis API match data to Google Calendar event format.

    Args:
        match: Match data from Tennis API
        followed_player_name: Name of the player being followed (for highlighting)

    Returns:
        Dictionary ready for Google Calendar API
    """
    # Extract player names
    home_player = match.get("event_home_player", "TBD")
    away_player = match.get("event_away_player", "TBD")

    # Tournament info
    tournament = match.get("tournament_name", "Tennis Match")
    round_name = match.get("event_round", "")
    surface = match.get("event_surface", "")
    stadium = match.get("event_stadium", "")

    # Build summary
    # If we know which player is being followed, put them first
    if followed_player_name:
        if followed_player_name.lower() in home_player.lower():
            player_order = f"{home_player} vs {away_player}"
        elif followed_player_name.lower() in away_player.lower():
            player_order = f"{away_player} vs {home_player}"
        else:
            player_order = f"{home_player} vs {away_player}"
    else:
        player_order = f"{home_player} vs {away_player}"

    # Create summary with tournament and round
    if round_name:
        summary = f"{tournament} {round_name}: {player_order}"
    else:
        summary = f"{tournament}: {player_order}"

    # Truncate if too long
    if len(summary) > 100:
        summary = summary[:97] + "..."

    # Build description
    description_parts = [
        f"Tennis Match - {tournament}",
        "",
        f"{home_player} vs {away_player}",
        "",
    ]

    if round_name:
        description_parts.append(f"Round: {round_name}")
    if surface:
        description_parts.append(f"Surface: {surface}")
    if stadium:
        description_parts.append(f"Court: {stadium}")

    description_parts.extend([
        "",
        "---",
        "Auto-generated by SportsWatcher Tennis Tracker",
        "https://github.com/your-repo/sportswatcher",
    ])

    description = "\n".join(description_parts)

    # Parse datetime
    event_date = match.get("event_date", "")
    event_time = match.get("event_time", "")

    start_time = parse_event_datetime(event_date, event_time)

    # Tennis matches typically last 2-3 hours, use 3 as estimate
    end_time = start_time + timedelta(hours=3)

    # Location
    location = stadium if stadium else tournament

    return {
        "summary": summary,
        "description": description,
        "start_time": start_time.isoformat(),
        "end_time": end_time.isoformat(),
        "location": location,
        "timezone": "UTC",
    }


def parse_event_datetime(date_str: str, time_str: str = "") -> datetime:
    """
    Parse date and time strings from the API into a datetime object.

    Handles various formats the API might return.

    Args:
        date_str: Date string (e.g., "2026-01-20" or "2026-01-20 14:00:00")
        time_str: Optional separate time string

    Returns:
        datetime object in UTC
    """
    # If date_str already contains time
    if " " in date_str and not time_str:
        try:
            return datetime.fromisoformat(date_str.replace("Z", "+00:00").replace("+00:00", ""))
        except ValueError:
            pass

    # Try parsing date only
    try:
        date = datetime.strptime(date_str[:10], "%Y-%m-%d")
    except ValueError:
        # Fallback to now + 1 day if parsing fails
        return datetime.utcnow() + timedelta(days=1)

    # Add time if provided
    if time_str:
        try:
            time_parts = time_str.split(":")
            date = date.replace(
                hour=int(time_parts[0]),
                minute=int(time_parts[1]) if len(time_parts) > 1 else 0,
            )
        except (ValueError, IndexError):
            pass

    return date


def calculate_event_hash(match: dict) -> str:
    """
    Calculate a hash of match details for change detection.

    Used to determine if a calendar event needs updating.

    Args:
        match: Match data from Tennis API

    Returns:
        MD5 hash of key match fields
    """
    # Fields that affect the calendar event
    key_fields = [
        str(match.get("event_date", "")),
        str(match.get("event_time", "")),
        str(match.get("event_home_player", "")),
        str(match.get("event_away_player", "")),
        str(match.get("event_stadium", "")),
        str(match.get("event_round", "")),
        str(match.get("event_status", "")),
    ]

    content = "|".join(key_fields)
    return hashlib.md5(content.encode()).hexdigest()


def format_match_status(status: str) -> str:
    """
    Format match status for display.

    Args:
        status: Raw status from API

    Returns:
        Human-readable status
    """
    status_map = {
        "NS": "Not Started",
        "LIVE": "Live",
        "FT": "Finished",
        "CANC": "Cancelled",
        "POSTP": "Postponed",
        "ABD": "Abandoned",
        "WO": "Walkover",
        "RET": "Retired",
    }
    return status_map.get(status.upper(), status)


def is_match_relevant(match: dict) -> bool:
    """
    Check if a match should be synced to the calendar.

    Filters out completed, cancelled, or invalid matches.

    Args:
        match: Match data from Tennis API

    Returns:
        True if match should be synced
    """
    status = match.get("event_status", "").lower()

    # Skip completed or cancelled matches
    # TennisApi1 uses: "inprogress", "finished", "notstarted"
    skip_statuses = {"finished", "ft", "canc", "abd", "wo", "cancelled"}
    if status in skip_statuses:
        return False

    # Must have a valid date or start timestamp
    event_date = match.get("event_date", "")
    start_timestamp = match.get("start_timestamp", 0)
    if not event_date and not start_timestamp:
        return False

    # Must have player info
    if not match.get("event_home_player") or not match.get("event_away_player"):
        return False

    return True
